export interface SequenceSettingRowDto {
  id: number;
  name: string;
  sequenceLength: number;
  module: string;
  documentType: string;
  sequenceType: string;
  startsFrom: number;
  increment: number;
  lastValue: number;
  resetEveryYear: boolean;
  isActive: boolean;
}

/** بيانات ثابتة مطابقة لشاشة Ultimate — إعدادات التسلسل */
export const SEQUENCE_SETTINGS_SEED: SequenceSettingRowDto[] = [
  {
    id: 1,
    name: 'تسلسل إلغاء الحجز',
    sequenceLength: 0,
    module: 'الحجوزات',
    documentType: 'إلغاء الحجز',
    sequenceType: 'عام - تلقائي',
    startsFrom: 1,
    increment: 1,
    lastValue: 0,
    resetEveryYear: true,
    isActive: true,
  },
  {
    id: 2,
    name: 'تسلسل الإشعار الدائن',
    sequenceLength: 0,
    module: 'الحجوزات',
    documentType: 'إشعار دائن',
    sequenceType: 'مركب - مقاطع',
    startsFrom: 1,
    increment: 1,
    lastValue: 0,
    resetEveryYear: true,
    isActive: true,
  },
  {
    id: 3,
    name: 'تسلسل الإشعار المدين',
    sequenceLength: 0,
    module: 'الحجوزات',
    documentType: 'إشعار مدين',
    sequenceType: 'مركب - مقاطع',
    startsFrom: 1,
    increment: 1,
    lastValue: 0,
    resetEveryYear: true,
    isActive: true,
  },
  {
    id: 4,
    name: 'تسلسل الألوتمنت (Allotment)',
    sequenceLength: 0,
    module: 'الحجوزات',
    documentType: 'حجز مخصص',
    sequenceType: 'عام - تلقائي',
    startsFrom: 1,
    increment: 1,
    lastValue: 0,
    resetEveryYear: true,
    isActive: true,
  },
  {
    id: 5,
    name: 'تسلسل الحجز',
    sequenceLength: 0,
    module: 'الحجوزات',
    documentType: 'حجز',
    sequenceType: 'عام - تلقائي',
    startsFrom: 1,
    increment: 1,
    lastValue: 576,
    resetEveryYear: true,
    isActive: true,
  },
  {
    id: 6,
    name: 'تسلسل حجز مجموعة',
    sequenceLength: 0,
    module: 'الحجوزات',
    documentType: 'حجز مجموعة',
    sequenceType: 'عام - تلقائي',
    startsFrom: 1,
    increment: 1,
    lastValue: 29,
    resetEveryYear: true,
    isActive: true,
  },
  {
    id: 7,
    name: 'تسلسل تعديل الحجز',
    sequenceLength: 0,
    module: 'الحجوزات',
    documentType: 'تعديل الحجز',
    sequenceType: 'عام - تلقائي',
    startsFrom: 1,
    increment: 1,
    lastValue: 0,
    resetEveryYear: true,
    isActive: true,
  },
  {
    id: 8,
    name: 'تسلسل نقل الحجز',
    sequenceLength: 0,
    module: 'الحجوزات',
    documentType: 'نقل الحجز',
    sequenceType: 'عام - تلقائي',
    startsFrom: 1,
    increment: 1,
    lastValue: 0,
    resetEveryYear: true,
    isActive: true,
  },
  {
    id: 9,
    name: 'تسلسل حساب الشركات',
    sequenceLength: 0,
    module: 'إدارة النزلاء',
    documentType: 'حساب الشركات',
    sequenceType: 'عام - تلقائي',
    startsFrom: 1,
    increment: 1,
    lastValue: 0,
    resetEveryYear: true,
    isActive: true,
  },
  {
    id: 10,
    name: 'تسلسل الصرف',
    sequenceLength: 0,
    module: 'الاستقبال',
    documentType: 'صرف',
    sequenceType: 'عام - تلقائي',
    startsFrom: 1,
    increment: 1,
    lastValue: 3,
    resetEveryYear: true,
    isActive: true,
  },
  {
    id: 11,
    name: 'تسلسل الدفع',
    sequenceLength: 0,
    module: 'الاستقبال',
    documentType: 'دفع',
    sequenceType: 'عام - تلقائي',
    startsFrom: 1,
    increment: 1,
    lastValue: 97,
    resetEveryYear: true,
    isActive: true,
  },
  {
    id: 12,
    name: 'تسلسل الإيداع',
    sequenceLength: 0,
    module: 'الاستقبال',
    documentType: 'إيداع',
    sequenceType: 'عام - تلقائي',
    startsFrom: 1,
    increment: 1,
    lastValue: 0,
    resetEveryYear: true,
    isActive: true,
  },
];
